#!/bin/sh
# Wrap our U-Boot in a FIT that the stock QNAP/QCA U-Boot boots like a kernel
# (chainload stage, docs/fit.md "The loader FIT"). The stock bootipq only
# accepts a configuration named "config@hk01".
#
# usage: tools/mkloader.sh [u-boot build dir] [output .itb]
# Runs mkimage inside the build container; paths are relative to the repo.
set -eu
root=$(cd "$(dirname "$0")/.." && pwd)
build=${1:-build/u-boot-301w}
out=${2:-build/loader/qnap_301w-uboot-loader.itb}
dtb=$build/arch/arm/dts/ipq8072-qnap-301w.dtb

# Load/entry: where the stock bootm copies our U-Boot before jumping to it
# through the TrustZone monitor. 0x41000000 is where OpenWrt's kernel loads
# today, clear of the FIT staging area (0x44000000) and of the reserved
# bootloader/SBL/SMEM/TZ region at 0x4a600000-0x4affffff.
load=0x41000000

for f in "$root/$build/u-boot.bin" "$root/$dtb"; do
	[ -f "$f" ] || { echo "missing $f (build U-Boot first)" >&2; exit 1; }
done
mkdir -p "$root/$(dirname "$out")"
its="$root/$(dirname "$out")/loader.its"

cat > "$its" <<EOF
/dts-v1/;

/ {
	description = "U-Boot for QNAP QHora-301W, chainloaded by the stock U-Boot";
	#address-cells = <1>;

	images {
		kernel@1 {
			description = "U-Boot $(sed -n 's/^#define PLAIN_VERSION "\(.*\)"/\1/p' "$root/$build/include/generated/version_autogenerated.h")";
			data = /incbin/("/work/$build/u-boot.bin");
			type = "kernel";
			arch = "arm64";
			os = "linux";
			compression = "none";
			load = <$load>;
			entry = <$load>;
			hash@1 { algo = "crc32"; };
			hash@2 { algo = "sha1"; };
		};

		fdt@hk01 {
			description = "QNAP QHora-301W (U-Boot device tree)";
			data = /incbin/("/work/$dtb");
			type = "flat_dt";
			arch = "arm64";
			compression = "none";
			hash@1 { algo = "crc32"; };
			hash@2 { algo = "sha1"; };
		};
	};

	configurations {
		default = "config@hk01";

		config@hk01 {
			description = "U-Boot (chainload)";
			kernel = "kernel@1";
			fdt = "fdt@hk01";
		};
	};
};
EOF

"$root/tools/build/run.sh" sh -c "mkimage -f /work/${its#$root/} /work/$out >/dev/null && dumpimage -l /work/$out"
ls -l "$root/$out"
shasum -a 256 "$root/$out"
